spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/viatab
spring.datasource.username=viatab
spring.datasource.password=viatab

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
